"use client";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { ContextProvider } from "../../context/ContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <Navbar />
          {children}
        </body>
      </html>
    </ContextProvider>
  );
}
