"use client";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { ThirdwebProvider } from "@thirdweb-dev/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThirdwebProvider>
          <Navbar />
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
