"use client";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { ThirdwebProvider } from "@thirdweb-dev/react";
import { Sepolia } from "@thirdweb-dev/chains";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThirdwebProvider
      activeChain={Sepolia}
      clientId="b119ec5ba98f85ef8edf0347e1c2c589">
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <Navbar />
          {children}
        </body>
      </html>
    </ThirdwebProvider>
  );
}
